/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LAB8BBR90Is
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { CardContent, Card } from "@/components/ui/card";

type SummaryCardProps = {
  headline: string;
  context: string;
  discussionPoints: string;
  takeaways: string;
};

export function SummaryCard({
  headline,
  discussionPoints,
  takeaways,
  context
}: SummaryCardProps) {
  return (
    <Card>
      <CardContent className="space-y-4">
        <h2 className="text-xl font-semibold pt-4">{headline}</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm">
          <li>{context}</li>
          <li>{discussionPoints}</li>
          <li>{takeaways}</li>
        </ul>
      </CardContent>
    </Card>
  );
}
